<script lang="ts">
  import { DUOTONE_ICON_BODIES } from "../bodies.generated";

  export let size: string | number = 24;
  export let color: string | undefined = undefined;
  // Duotone is a single weight; the prop stays accepted (and unused) so these
  // components drop in wherever reicon-svelte components are expected.
  // svelte-ignore export_let_unused
  export let weight: "Outline" | "Filled" = "Outline";
  // svelte-ignore export_let_unused
  export let strokeWidth: string | number | undefined = undefined;

  let className = "";
  export { className as class };

  let customStyle = "";
  export { customStyle as style };

  const body = DUOTONE_ICON_BODIES["Folder"];
</script>

<!--
  Generated by scripts/generate-duotone-icons.mjs — do not edit.
  Folder (Reicon duotone weight), props contract matches reicon-svelte components.
-->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width={size}
  height={size}
  viewBox="0 0 24 24"
  fill="none"
  class="reicon duotone {className}"
  style={color != null ? `color: ${color}; ${customStyle}` : customStyle}
  aria-hidden="true"
  focusable="false"
  {...$$restProps}
>
  {@html body}
</svg>
