const strings = {
  en: { title:"Meeting Notes",subtitle:"Record, transcribe, and recover meeting notes.",newMeeting:"New meeting",stop:"Stop and generate notes",empty:"No meetings yet.",select:"Select a meeting.",permission:"Microphone access was denied.",recording:"Recording",delete:"Delete meeting",confirmAction:"Confirm permanent delete",rename:"Rename",regenerate:"Regenerate notes",retry:"Retry",segments:"Segments",audio:"Audio retained",confirmDelete:"Click confirm again to permanently delete this meeting and all retained audio.",interrupted:"Interrupted — retry failed segments or regenerate from completed text.",
        state:{ recording:"Recording",transcribing:"Transcribing",summarizing:"Summarizing",complete:"Complete",failed:"Failed",interrupted:"Interrupted",queued:"Queued" } },
  zh: { title:"会议纪要",subtitle:"录音、逐段转写，并在中断后恢复。",newMeeting:"新建会议",stop:"停止并生成纪要",empty:"还没有会议。",select:"选择一场会议。",permission:"麦克风权限被拒绝。",recording:"录音中",delete:"删除会议",confirmAction:"确认永久删除",rename:"重命名",regenerate:"重新生成纪要",retry:"重试",segments:"分段",audio:"原始音频已保留",confirmDelete:"请再次点击确认，永久删除这场会议及全部原始音频。",interrupted:"处理被中断，可重试失败分段或用已有文本重新生成。",
        state:{ recording:"录音中",transcribing:"转写中",summarizing:"生成纪要中",complete:"已完成",failed:"失败",interrupted:"已中断",queued:"排队中" } }
};
const params=new URLSearchParams(location.search);const locale=String(params.get("locale")||"en").startsWith("zh")?"zh":"en";const t=strings[locale];document.documentElement.lang=locale==="zh"?"zh-CN":"en";document.documentElement.dataset.theme=params.get("theme")==="dark"?"dark":"light";document.querySelectorAll("[data-i18n]").forEach(n=>n.textContent=t[n.dataset.i18n]||n.textContent);
const el={new:document.getElementById("new"),stop:document.getElementById("stop"),status:document.getElementById("status"),recording:document.getElementById("recording"),recordingTitle:document.getElementById("recording-title"),timer:document.getElementById("timer"),list:document.getElementById("meetings"),empty:document.getElementById("empty"),detail:document.getElementById("detail")};
let meetings=[],selected="",stream=null,recorder=null,meetingId="",seq=0,started=0,segmentTimer=null,clockTimer=null,pending=[],stopping=false;
// Deep-link landing. `molibot://miniapp/meeting-notes/meeting/<id>` arrives as a
// `?path=` startup hint beside locale/theme; the host never interprets it, this
// app defines the `meeting/<id>` shape. Seeding `selected` is all that is
// needed: the initial load() shows it and renderList() marks it active. A stale
// id simply shows nothing selected rather than failing.
{const parts=String(params.get("path")||"").split("/");if(parts[0]==="meeting"&&parts[1])selected=parts[1];}
function status(message,error=false){el.status.hidden=!message;el.status.textContent=message||"";el.status.dataset.error=String(error);}
async function api(path,init={}){const response=await fetch(`./api${path}`,{...init,headers:{...(init.body instanceof Blob?{"content-type":init.body.type||"audio/webm"}:{"content-type":"application/json"}),...(init.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body;}
function escapeHtml(value){return String(value||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]);}
// A status chip carries its own label AND a tone, so state never rests on
// colour alone. An unknown status from a newer server still renders — it keeps
// the raw value and the neutral tone rather than disappearing.
function stateLabel(value){return t.state[value]||String(value||"");}
function stateTone(value){
  if(value==="complete")return "done";
  if(value==="failed"||value==="interrupted")return "alert";
  if(value==="recording"||value==="transcribing"||value==="summarizing"||value==="queued")return "busy";
  return "neutral";
}
function chip(value,extra=""){return `<span class="chip${extra}" data-tone="${stateTone(value)}">${escapeHtml(stateLabel(value))}</span>`;}
async function load(){const data=await api("/meetings");meetings=data.meetings;renderList();if(selected)await show(selected);}
function renderList(){el.empty.hidden=meetings.length>0;el.list.replaceChildren(...meetings.map(m=>{const li=document.createElement("li");const b=document.createElement("button");b.type="button";b.className=m.id===selected?"meeting-item active":"meeting-item";b.innerHTML=`<span class="meeting-item-title">${escapeHtml(m.title)}</span>${chip(m.status," chip-sm")}`;b.onclick=()=>{selected=m.id;void show(m.id);renderList();};li.append(b);return li;}));}
async function show(id){const {meeting}=await api(`/meetings/${encodeURIComponent(id)}`);if(!meeting){el.detail.innerHTML=`<p class="placeholder">${escapeHtml(t.select)}</p>`;return;}const bytes=meeting.segments.reduce((sum,s)=>sum+s.bytes,0);el.detail.innerHTML=`<div class="detail-head"><div class="detail-head-main"><input id="meeting-title" class="title-field" value="${escapeHtml(meeting.title)}">${chip(meeting.status)}</div><div class="detail-actions"><button id="regenerate" class="btn btn-tonal">${t.regenerate}</button><button id="delete" class="btn btn-text btn-danger">${t.delete}</button></div></div>${meeting.status==="interrupted"?`<p class="banner" data-error="true">${t.interrupted}</p>`:""}<p class="storage">${t.audio}: ${(bytes/1024/1024).toFixed(1)} MiB</p><section class="summary">${meeting.summary?`<pre>${escapeHtml(meeting.summary)}</pre>`:""}</section><h2 class="section-title">${t.segments}</h2><ol class="segments">${meeting.segments.map(s=>`<li class="segment"><span class="segment-index">${s.seq+1}</span><div class="segment-body"><div class="segment-meta">${chip(s.status," chip-sm")}</div><p class="segment-text">${escapeHtml(s.text||s.error)}</p>${["failed","interrupted"].includes(s.status)?`<button class="btn btn-text" data-retry="${s.id}">${t.retry}</button>`:""}</div></li>`).join("")}</ol>`;
  document.getElementById("meeting-title").onchange=e=>void api(`/meetings/${id}`,{method:"PATCH",body:JSON.stringify({title:e.target.value})}).then(load).catch(e=>status(e.message,true));document.getElementById("regenerate").onclick=()=>void api(`/meetings/${id}/regenerate`,{method:"POST",body:"{}"}).then(load).catch(e=>status(e.message,true));const deleteButton=document.getElementById("delete");deleteButton.onclick=()=>{if(deleteButton.dataset.armed!=="true"){deleteButton.dataset.armed="true";deleteButton.textContent=t.confirmAction;status(t.confirmDelete,true);return;}void api(`/meetings/${id}`,{method:"DELETE"}).then(()=>{selected="";el.detail.innerHTML=`<p class="placeholder">${escapeHtml(t.select)}</p>`;status("");return load();}).catch(e=>status(e.message,true));};el.detail.querySelectorAll("[data-retry]").forEach(b=>b.onclick=()=>void api(`/segments/${b.dataset.retry}/retry`,{method:"POST",body:"{}"}).then(()=>show(id)).catch(e=>status(e.message,true)));}
function formatClock(){const seconds=Math.floor((Date.now()-started)/1000);el.timer.textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;}
function startRecorder(){const segmentChunks=[];const currentRecorder=new MediaRecorder(stream);recorder=currentRecorder;currentRecorder.ondataavailable=e=>{if(e.data.size)segmentChunks.push(e.data);};currentRecorder.onstop=()=>{const blob=new Blob(segmentChunks,{type:currentRecorder.mimeType||"audio/webm"});const current=seq++;const upload=api(`/segments/${meetingId}?seq=${current}`,{method:"POST",body:blob}).catch(e=>{status(e.message,true);return null;});pending.push(upload);};currentRecorder.onerror=e=>status(e.error?.message||"Recorder error",true);currentRecorder.start();segmentTimer=setTimeout(()=>{if(currentRecorder.state==="recording"){currentRecorder.addEventListener("stop",()=>{if(stream)startRecorder();},{once:true});currentRecorder.stop();}},60000);}
async function begin(){try{stopping=false;if(!window.MediaRecorder)throw new Error("MediaRecorder is unavailable.");stream=await navigator.mediaDevices.getUserMedia({audio:true});const created=await api("/meetings",{method:"POST",body:JSON.stringify({})});meetingId=created.meeting.id;stream.getTracks().forEach(track=>track.addEventListener("ended",()=>{if(!stopping){status("Audio device disconnected.",true);void stop();}},{once:true}));selected=meetingId;seq=0;pending=[];started=Date.now();el.recording.hidden=false;el.recordingTitle.textContent=created.meeting.title;clockTimer=setInterval(formatClock,1000);startRecorder();await load();}catch(e){stopping=true;stream?.getTracks().forEach(track=>track.stop());stream=null;status(e.name==="NotAllowedError"?t.permission:e.message,true);}}
async function stop(){if(stopping)return;stopping=true;clearTimeout(segmentTimer);clearInterval(clockTimer);if(recorder?.state==="recording"){await new Promise(resolve=>{recorder.addEventListener("stop",resolve,{once:true});recorder.stop();});}const activeStream=stream;stream=null;activeStream?.getTracks().forEach(track=>track.stop());el.recording.hidden=true;await Promise.allSettled(pending);try{await api(`/meetings/${meetingId}/finish`,{method:"POST",body:"{}"});await load();}catch(e){status(e.message,true);await load();}}
el.new.onclick=()=>void begin().catch(e=>status(e.message,true));el.stop.onclick=()=>void stop().catch(e=>status(e.message,true));window.addEventListener("pagehide",()=>{stopping=true;clearTimeout(segmentTimer);clearInterval(clockTimer);stream?.getTracks().forEach(track=>track.stop());});void load().catch(e=>status(e.message,true));
